image: node:20

stages:
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm ci
    - npm run lint
    - npm run test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy:
  stage: deploy
  script:
    - npm run export
    - npm run deploy:gitlab-pages
  environment:
    name: production
    url: https://dev-moe-kyawaung.gitlab.io/portfolio
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  dependencies:
    - build
  only:
    - main
